name: "Solved.ac Add-on"
description: "Fetch and display today's solved problems from solved.ac"
version: "1.0.0"
slug: "solved_ac_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
ports:
  "5000/tcp": 5000
webui: "http://[HOST]:[PORT:5000]"
options:
  handle: "happyicus1"
schema:
  handle: "str"